#!/usr/bin/env python3
"""
Build comprehensive voice_action_mapping.csv from runtime IL analysis data.

Data sources:
- deep_voice_analysis.txt: Runtime IL scan from MelonLoader mod v2
- Partner.xml files: Partner voice cue field data
- System Voice Cue Map: 156 entries (Mai2.Voice_000001.Cue)
- Partner Voice Cue Map: 94 entries (Mai2.Voice_Partner_000001.Cue)
"""
import csv

# ============================================================
# CUE MAPS (from runtime reflection)
# ============================================================

# System Voice: VO_ID -> cue index in Voice_000001.acb
SYSTEM_VOICE_MAP = {
    "VO_000001": 0,   "VO_000002": 1,   "VO_000003": 2,   "VO_000004": 3,
    "VO_000005": 4,   "VO_000006": 5,   "VO_000007": 6,   "VO_000008": 7,
    "VO_000009": 8,   "VO_000011": 10,  "VO_000012": 11,  "VO_000013": 12,
    "VO_000015": 14,  "VO_000016": 15,  "VO_000017": 16,  "VO_000018": 17,
    "VO_000019": 18,  "VO_000020": 19,  "VO_000022": 21,  "VO_000024": 23,
    "VO_000026": 25,  "VO_000027": 26,  "VO_000028": 27,  "VO_000029": 28,
    "VO_000030": 29,  "VO_000031": 30,  "VO_000032": 31,  "VO_000033": 32,
    "VO_000034": 33,  "VO_000035": 34,  "VO_000036": 35,  "VO_000037": 36,
    "VO_000038": 37,  "VO_000040": 39,  "VO_000041": 40,  "VO_000042": 41,
    "VO_000043": 42,  "VO_000044": 43,  "VO_000045": 44,  "VO_000046": 45,
    "VO_000047": 46,  "VO_000048": 47,  "VO_000049": 48,  "VO_000050": 49,
    "VO_000051": 50,  "VO_000052": 51,  "VO_000053": 52,  "VO_000054": 53,
    "VO_000055": 54,  "VO_000056": 55,  "VO_000057": 56,  "VO_000058": 57,
    "VO_000059": 58,  "VO_000060": 59,  "VO_000061": 60,  "VO_000062": 61,
    "VO_000063": 62,  "VO_000065": 64,  "VO_000066": 65,  "VO_000075": 74,
    "VO_000076": 75,  "VO_000077": 76,  "VO_000089": 88,  "VO_000090": 89,
    "VO_000091": 90,  "VO_000110": 109, "VO_000111": 110, "VO_000142": 141,
    "VO_000143": 142, "VO_000144": 143, "VO_000145": 144, "VO_000146": 145,
    "VO_000147": 146, "VO_000148": 147, "VO_000149": 148, "VO_000150": 149,
    "VO_000154": 153, "VO_000156": 155, "VO_000163": 162, "VO_000169": 168,
    "VO_000170": 169, "VO_000171": 170, "VO_000172": 171, "VO_000173": 172,
    "VO_000174": 173, "VO_000176": 175, "VO_000177": 176, "VO_000178": 177,
    "VO_000179": 178, "VO_000180": 179, "VO_000181": 180, "VO_000183": 182,
    "VO_000185": 184, "VO_000186": 185, "VO_000205": 204, "VO_000207": 206,
    "VO_000208": 207, "VO_000209": 208, "VO_000210": 209, "VO_000223": 222,
    "VO_000224": 223, "VO_000225": 224, "VO_000226": 225, "VO_000227": 226,
    "VO_000228": 227, "VO_000229": 228, "VO_000230": 229, "VO_000231": 230,
    "VO_000232": 231, "VO_000235": 234, "VO_000238": 237, "VO_000239": 238,
    "VO_000240": 239, "VO_000241": 240, "VO_000242": 241, "VO_000255": 242,
    "VO_000256": 243, "VO_000257": 244, "VO_000258": 245, "VO_000259": 246,
    "VO_000260": 247, "VO_000261": 248, "VO_000262": 249, "VO_000263": 250,
    "VO_000103": 251, "VO_000104": 252, "VO_000109": 253, "VO_000112": 254,
    "VO_000114": 255, "VO_000206": 256, "VO_000099": 257, "VO_000101": 258,
    "VO_000133": 259, "VO_000151": 260, "VO_000152": 261, "VO_000153": 262,
    "VO_000155": 263, "VO_000157": 264, "VO_000158": 265, "VO_000159": 266,
    "VO_000182": 267, "VO_000184": 268, "VO_000187": 269, "VO_000188": 270,
    "VO_000189": 271, "VO_000247": 272, "VO_000248": 273, "VO_000253": 274,
    "VO_000264": 275, "VO_000265": 276,
}

# Partner Voice: VO_ID -> cue index in Voice_Partner_XXXXXX.acb
PARTNER_VOICE_MAP = {
    "VO_000080": 0,   "VO_000081": 1,   "VO_000084": 2,   "VO_000085": 3,
    "VO_000086": 4,   "VO_000087": 5,   "VO_000088": 6,   "VO_000099": 7,
    "VO_000101": 8,   "VO_000113": 9,   "VO_000114": 10,  "VO_000116": 11,
    "VO_000118": 12,  "VO_000119": 13,  "VO_000120": 14,  "VO_000121": 15,
    "VO_000122": 16,  "VO_000123": 17,  "VO_000124": 18,  "VO_000125": 19,
    "VO_000126": 20,  "VO_000127": 21,  "VO_000128": 22,  "VO_000129": 23,
    "VO_000130": 24,  "VO_000131": 25,  "VO_000133": 26,  "VO_000139": 27,
    "VO_000141": 28,  "VO_000151": 29,  "VO_000152": 30,  "VO_000153": 31,
    "VO_000155": 32,  "VO_000157": 33,  "VO_000158": 34,  "VO_000159": 35,
    "VO_000164": 36,  "VO_000165": 37,  "VO_000166": 38,  "VO_000167": 39,
    "VO_000182": 40,  "VO_000184": 41,  "VO_000187": 42,  "VO_000188": 43,
    "VO_000189": 44,  "VO_000200": 45,  "VO_000201": 46,  "VO_000202": 47,
    "VO_000203": 48,  "VO_000204": 49,  "VO_000211": 50,  "VO_000213": 51,
    "VO_000214": 52,  "VO_000217": 53,  "VO_000220": 54,  "VO_000222": 55,
    "VO_000244": 56,  "VO_000245": 57,  "VO_000246": 58,  "VO_000247": 59,
    "VO_000082": 60,  "VO_000083": 61,  "VO_000115": 62,  "VO_000117": 63,
    "VO_000248": 64,  "VO_000249": 65,  "VO_000250": 66,  "VO_000251": 67,
    "VO_000252": 68,  "VO_000103": 69,  "VO_000104": 70,  "VO_000109": 71,
    "VO_000112": 72,  "VO_000190": 73,  "VO_000191": 74,  "VO_000192": 75,
    "VO_000193": 76,  "VO_000194": 77,  "VO_000195": 78,  "VO_000196": 79,
    "VO_000197": 80,  "VO_000198": 81,  "VO_000199": 82,  "VO_000206": 84,
    "VO_000243": 85,  "VO_000253": 86,  "VO_000254": 87,  "VO_000142": 88,
    "VO_000207": 89,  "VO_000208": 90,  "VO_000209": 91,  "VO_000210": 92,
    "VO_000265": 93,  "VO_000266": 94,
}

# Inverse maps for index -> VO_ID lookup
SYS_INV = {v: k for k, v in SYSTEM_VOICE_MAP.items()}
PTR_INV = {v: k for k, v in PARTNER_VOICE_MAP.items()}

# ============================================================
# CONFIRMED MAPPINGS FROM RUNTIME IL SCAN
# Source: deep_voice_analysis.txt scan section (lines 291-2214)
# Method: Filtered for SoundManager.PlayVoice, PlayPartnerVoice,
#         PlayAdvertiseVoice, and voice wrapper calls.
#         Excluded Animator.Play, NavigationCharacter.Play, and
#         other non-voice methods that were false positives.
#         Small integer values (0-2) at same IL offset as larger
#         values are classified as target parameters, not cues.
# ============================================================

# Format: (VO_ID, game_context, caller_methods, evidence, notes)
SYSTEM_VOICE_DATA = [
    # --- Entry / Login ---
    ("VO_000001", "Entry / General system voice", 
     "ModeSelectMonitor.ViewUpdate; AdvDemoProcess.OnUpdate; CharacterSelectProces.PostReset; NameEntryProcess.OnUpdate",
     "Confirmed", "Used across multiple screens. Often appears as target param (0=both monitors) but also as a conditional cue in mode selection and character select."),
    ("VO_000002", "Entry / General system voice",
     "ModeSelectMonitor.ViewUpdate; CharacterSelectProces.PostReset; PhotoShootProcess.ChangeCountDownSound; TutorialSelectProces.OnUpdate",
     "Confirmed", "Appears in mode select branches, photo countdown, and tutorial. Sometimes used as target param (1=player 1)."),
    ("VO_000003", "Entry / General system voice",
     "AdvertiseProcess.OnUpdate (PlayVoice); CharacterSelectProces.PostReset; PhotoEditProcess.MainMenuUpdate; TutorialSelectProces.OnUpdate",
     "Confirmed", "Advertise screen voice; appears in character select, photo edit, tutorial select."),
    ("VO_000004", "Mode select / Photo sequence voice",
     "ModeSelectMonitor.ViewUpdate; AdvDemoProcess.OnUpdate; PhotoShootProcess.EnterPhotographingSequence; SimpleSettingProcess.EnterPhotographingSequence; RegionalSelectProcess.RegionSelectDecide",
     "Confirmed", "Mode selection voice; photo sequence entrance; regional select voice."),
    ("VO_000005", "Mode select / Ticket select voice",
     "ModeSelectMonitor.ViewUpdate; CharacterSelectProces.PostReset; TicketSelectMonitor.ViewUpdate; PlayAdvertiseVoice calls",
     "Confirmed", "Mode select branch voice; ticket select screen; advertise voice."),
    ("VO_000006", "Entry confirmation voice",
     "Process.Entry.State.ConfirmEntry.Exec (via StateEntry.PlayVoice)",
     "Confirmed", "Played when entry is confirmed. Conditional with VO_000001."),
    ("VO_000007", "Ticket select voice",
     "Monitor.TicketSelect.TicketSelectMonitor.ViewUpdate",
     "Confirmed", "Plays during ticket selection screen updates."),
    ("VO_000008", "Photo countdown / General countdown",
     "PhotoShootProcess.ChangeCountDownSound; SimpleSettingProcess.ChangeCountDownSound",
     "Confirmed", "Countdown sound during photo shoot sequence. Part of 3-2-1 countdown set with VO_000031/VO_000032."),
    ("VO_000009", "Information screen voice",
     "Monitor.Information.InformationMonitor.ViewUpdate",
     "Confirmed", "Plays during information/announcement display."),
    
    # --- Core system voices (sequential block) ---
    ("VO_000011", "System / Result display",
     "FriendBattleResultMonitor.SetClassData; FriendSeasonRankingMonitor.PlayRankingSE (as SE)",
     "Inferred", "Used in friend battle result class data display. May be a ranking/tier voice."),
    ("VO_000012", "Please Wait countdown",
     "PleaseWaitProcess.OnUpdate → PleaseWaitMonitor.Play10CountDown",
     "Confirmed", "10-second countdown during Please Wait screen."),
    ("VO_000013", "System voice (sequential)",
     "", "Inferred", "Sequential block between VO_000012 and VO_000015. Likely countdown or wait-related."),
    ("VO_000015", "Collection screen update voice",
     "CollectionProcess.OnUpdate",
     "Confirmed", "Plays during collection screen interaction updates."),
    ("VO_000016", "Judge SE trigger (note judgment)",
     "NoteBase.Judge; NoteBase.JudgeToolate; HoldNote.JudgeHoldHead; BreakHoldNote.JudgeHoldHead; TouchHoldC.JudgeHoldHead; TouchNoteB.Judge",
     "Confirmed", "Internal trigger for note judgment sound effects. Used as parameter to PlayJudgeSe methods."),
    ("VO_000017", "Name entry interaction",
     "NameEntryProcess.OnUpdate",
     "Confirmed", "Voice during name entry update; paired with target param at same offset."),
    ("VO_000018", "Name entry confirm",
     "NameEntryMonitor.Input2Confirm",
     "Confirmed", "Voice when name input is confirmed (solo entry - no ambiguous values at this call)."),
    ("VO_000019", "Name entry completed",
     "NameEntryMonitor.GotoCompleted",
     "Confirmed", "Voice when name entry is complete and transitioning."),
    ("VO_000020", "Code read start",
     "Process.CodeRead.CodeReadProcess.StartLogic",
     "Confirmed", "Voice at the start of QR/barcode reading sequence. Called twice (two branches)."),
    ("VO_000022", "Code read / Card scan interaction",
     "CodeReadProcess.FirstInformationReadMessageComplete; CodeReadProcess.LogicUpdate; CodeReadProcess.UpdateInput",
     "Confirmed", "Voice during various code read states - first info complete, logic updates, input processing."),
    ("VO_000024", "System voice (gap fill)",
     "", "Inferred", "Between code read (VO_000022) and settings (VO_000026). Likely code-read or transition related."),
    ("VO_000026", "Simple setting voice",
     "SimpleSettingMonitor+<PlayCoroutine>.MoveNext",
     "Confirmed", "Voice during initial simple settings coroutine."),
    ("VO_000027", "Photo preparation voice",
     "PhotoShootProcess.EnterPhotographingSequence; SimpleSettingProcess.EnterPhotographingSequence",
     "Confirmed", "Voice when preparing the photo sequence. Plays after VO_000029."),
    ("VO_000028", "System voice (photo sequence block)",
     "", "Inferred", "Sequential between VO_000027 and VO_000029 in the photo sequence block."),
    ("VO_000029", "Photo notification / Entry voice",
     "PhotoShootProcess.EnterPhotographingSequence; SimpleSettingProcess.EnterPhotographingSequence",
     "Confirmed", "First voice when entering photo sequence. Also conditional with VO_000004."),
    ("VO_000030", "System voice (countdown block)",
     "", "Inferred", "Adjacent to countdown voices VO_000031/VO_000032. Likely part of countdown set."),
    ("VO_000031", "Photo countdown (3 or 2)",
     "PhotoShootProcess.ChangeCountDownSound; SimpleSettingProcess.ChangeCountDownSound",
     "Confirmed", "Part of photo countdown sequence. Called at different IL offsets from VO_000032."),
    ("VO_000032", "Photo countdown (1 or Go)",
     "PhotoShootProcess.ChangeCountDownSound; SimpleSettingProcess.ChangeCountDownSound",
     "Confirmed", "Part of photo countdown sequence. Appears twice at different offsets (likely 2 and 1 counts)."),
    ("VO_000033", "Character select lock SE",
     "CharacterSelectProces.Lock (via PlaySE)",
     "Confirmed", "Sound when locking in character selection. Note: This is the SE (sound effect) cue, not necessarily a voice line - same cue index space."),
    ("VO_000034", "System voice (settings block)",
     "", "Inferred", "Sequential after VO_000033, within settings/character block."),
    ("VO_000035", "System voice (settings block)",
     "", "Inferred", "Sequential within settings block, before VO_000036."),
    ("VO_000036", "Tutorial select voice",
     "TutorialSelectProces.OnUpdate",
     "Confirmed", "Voice during tutorial selection. Paired with VO_000002 and VO_000003 as conditional branches."),
    ("VO_000037", "System voice (selection block)",
     "", "Inferred", "Sequential within selection block."),
    ("VO_000038", "System voice (selection block)",
     "", "Inferred", "Adjacent to mode selection voices."),
    ("VO_000040", "System voice (gap - no idx 39 in enum due to VO_000039 missing)",
     "", "Inferred", "In system voice block after VO_000038. Note: VO_000039 not in system enum."),
    ("VO_000041", "System voice",
     "", "Inferred", "In the general system voice block. Note: also exists in partner voice map."),
    ("VO_000042", "System voice",
     "", "Inferred", "In the general system voice block."),
    ("VO_000043", "System voice",
     "", "Inferred", "Sequential system voice."),
    ("VO_000044", "System voice",
     "", "Inferred", "Sequential system voice."),
    ("VO_000045", "System voice",
     "", "Inferred", "Sequential system voice."),
    ("VO_000046", "System voice",
     "", "Inferred", "Sequential system voice."),
    ("VO_000047", "System voice",
     "", "Inferred", "Sequential system voice."),
    ("VO_000048", "System voice",
     "", "Inferred", "Sequential system voice."),
    ("VO_000049", "System voice",
     "", "Inferred", "Sequential system voice."),
    ("VO_000050", "System voice",
     "", "Inferred", "Sequential system voice."),
    ("VO_000051", "System voice",
     "", "Inferred", "Sequential system voice."),
    ("VO_000052", "System voice",
     "", "Inferred", "Sequential system voice."),
    ("VO_000053", "Unlock/reward fanfare SE",
     "FriendBattleResultMonitor.PlayUnlockInfo/PlayReliefInfo; KaleidxScopeTotalResultState+UnlockMusic; RegionalSelectProcess.RegionSelectDecide; UnlockMusicMonitor.PlayUnlockMusic; GhostResultMonitor.PlayUnlockInfo; LoginBonusMonitor.GetItemFadeIn_Update; FriendSeasonRankingMonitor.RewardFadeIn (all via PlaySE)",
     "Confirmed", "Unlock/reward jingle SE played across many screens when items/music/rewards are unlocked."),
    ("VO_000054", "Camera shutter SE",
     "PhotoShootProcess.UpdatePhotograph; SimpleSettingProcess.UpdatePhotograph; PhotoManager.Update (all via PlaySE)",
     "Confirmed", "Camera shutter sound effect during photo capture."),
    ("VO_000055", "System voice",
     "", "Inferred", "Sequential in system voice block."),
    ("VO_000056", "System voice",
     "", "Inferred", "Sequential in system voice block."),
    ("VO_000057", "System voice",
     "", "Inferred", "Sequential in system voice block."),
    ("VO_000058", "System voice",
     "", "Inferred", "Sequential before information voices."),
    ("VO_000059", "Information voice 1",
     "Monitor.Information.InformationMonitor.ViewUpdate",
     "Confirmed", "First information/announcement voice. Part of info display sequence with VO_000060 and VO_000061."),
    ("VO_000060", "Information voice 2",
     "Monitor.Information.InformationMonitor.ViewUpdate",
     "Confirmed", "Second information/announcement voice at separate IL offset from VO_000059."),
    ("VO_000061", "Information voice 3",
     "Monitor.Information.InformationMonitor.ViewUpdate",
     "Confirmed", "Third information/announcement voice at separate IL offset."),
    ("VO_000062", "System voice (music select BGM)",
     "MusicSelectProcess.ChangeBGM (via PlayBGM)",
     "Inferred", "Appears in BGM switch context. Cue index 61 - BGM select. Note: PlayBGM uses different ACB."),
    ("VO_000063", "System voice",
     "", "Inferred", "Sequential near VO_000062."),
    ("VO_000065", "Entry decided / Region decided voice",
     "Process.Entry.TryEntry.DecideEntry; Process.RegionalSelectProcess.Decide",
     "Confirmed", "Voice when player entry is decided or region is selected. Two distinct confirmed call sites."),
    ("VO_000066", "Regional discover voice",
     "RegionalDiscover.Next",
     "Confirmed", "Voice when discovering/advancing in regional feature."),
    
    # --- Special system voices (later additions, non-sequential indices) ---
    ("VO_000075", "System voice (high index block)",
     "", "Inferred", "Index 74. In the system voice block between VO_000066 and VO_000089."),
    ("VO_000076", "System voice (high index block)",
     "", "Inferred", "Index 75. Sequential with VO_000075."),
    ("VO_000077", "System voice (high index block)",
     "", "Inferred", "Index 76. Sequential with VO_000076."),
    ("VO_000089", "System voice",
     "", "Inferred", "Index 88. Isolated block."),
    ("VO_000090", "System voice",
     "", "Inferred", "Index 89. Sequential with VO_000089."),
    ("VO_000091", "System voice",
     "", "Inferred", "Index 90. Sequential with VO_000090."),
    
    # --- Character select / Music select ---
    ("VO_000110", "Character select / preview voice",
     "CharacterSelectProces.PostReset; CharacterSelectProces.UpdateCharactorSelect (x2)",
     "Confirmed", "Voice when character selection is reset or character is browsed. Called at IL offset 154 (separate from PostReset offset 128)."),
    ("VO_000111", "Character slot confirm voice",
     "CharacterSelectProces.SelectSlot",
     "Confirmed", "Voice when confirming a character slot selection. At IL offset 758."),
    
    # --- SE cues used by system (these are in the Voice_000001 cue sheet but play as SE) ---
    ("VO_000142", "SE: Tab button press",
     "TabButton.Pressed; MusicSelectSequence.ScoreKindMove; various OptionSelectSequence/GenreSelect/MenuSelect/SortSetting SE calls (all via PlaySE)",
     "Confirmed", "UI tab/navigation button press sound effect. Very frequently used across selection screens."),
    ("VO_000143", "SE: Scroll / Navigation tick",
     "GenreSelectSequence.ScrollUpdate; MenuSelectSequence.Update; MusicSelectSequence.ScrollUpdate; OptionSelectSequence.Update; SortSettingSequence.Update; many more (all via PlaySE)",
     "Confirmed", "UI scroll/navigation tick sound effect. The most frequently used SE in selection screens."),
    ("VO_000144", "Result / Map result voice",
     "Monitor.MapResultMonitor.ViewUpdate",
     "Confirmed", "Voice during map/result screen, plays alongside map result processing."),
    ("VO_000145", "SE: Confirm / Select press",
     "DifficultySelectSequence.Update; MusicSelectSequence.Update; PhotoShootProcess; MenuSelectSequence.Update; many more (via PlaySE)",
     "Confirmed", "UI confirm/select button press sound effect."),
    ("VO_000146", "SE: System (sequential)",
     "", "Inferred", "Sequential SE after VO_000145 in the SE cue block."),
    ("VO_000147", "SE: System (sequential)",
     "", "Inferred", "Sequential SE."),
    ("VO_000148", "SE: System (sequential)",
     "", "Inferred", "Sequential SE."),
    ("VO_000149", "SE: System (sequential)",
     "", "Inferred", "Sequential SE."),
    ("VO_000150", "SE: System (sequential)",
     "", "Inferred", "Sequential SE."),
    ("VO_000154", "Photo staging voice",
     "PhotoEditProcess.UpdateStaging",
     "Confirmed", "Voice during photo edit staging/preview phase."),
    ("VO_000156", "Collection information voice",
     "CollectionProcess.OnUpdate; CollectionProcess.InputInformationSequence",
     "Confirmed", "Voice during collection screen info display and information input sequence."),
    ("VO_000163", "Collection screen start voice",
     "CollectionProcess.OnStart",
     "Confirmed", "Voice when the collection/customization screen initializes."),
    
    # --- Extended feature voices ---
    ("VO_000169", "System voice (extended)",
     "", "Inferred", "Index 168. Start of extended voice block."),
    ("VO_000170", "System voice (extended)",
     "", "Inferred", "Index 169."),
    ("VO_000171", "System voice (extended)",
     "", "Inferred", "Index 170."),
    ("VO_000172", "Freedom/Free play confirmation voice",
     "Process.Entry.State.ConfirmFreedom.Init; Process.Entry.State.ConfirmFreedomOne.Init (via StateEntry.PlayVoice)",
     "Confirmed", "Voice for free play mode confirmation. Paired conditionally with VO_000002 (target)."),
    ("VO_000173", "System voice (extended)",
     "", "Inferred", "Index 172."),
    ("VO_000174", "System voice (extended)",
     "", "Inferred", "Index 173."),
    ("VO_000176", "Track start SE",
     "TrackStartMonitor.SetTrackStart (via PlaySE)",
     "Confirmed", "Sound effect when track/song start display appears."),
    ("VO_000177", "Collection get SE",
     "CollectionGetList.PrepareAddAnimation; CollectionGetList.PlayAddAnimation (via PlaySE)",
     "Confirmed", "Sound effect when getting/adding a collection item."),
    ("VO_000178", "Character select voice / slot voice",
     "CharacterSelectProces.PostReset; CharacterSelectProces.SelectSlot",
     "Confirmed", "Voice during character selection reset and slot selection."),
    ("VO_000179", "Character select voice",
     "CharacterSelectProces.PostReset",
     "Confirmed", "Voice during character selection reset sequence."),
    ("VO_000180", "Character select voice",
     "CharacterSelectProces.PostReset",
     "Confirmed", "Voice during character selection reset sequence."),
    ("VO_000181", "System voice (character block)",
     "", "Inferred", "Sequential after VO_000180 in character voice block."),
    ("VO_000183", "Code read SE",
     "CodeReadProcess.LogicUpdate (via PlaySE)",
     "Confirmed", "Sound effect during code read logic processing."),
    ("VO_000185", "System voice (extended)",
     "", "Inferred", "Index 184."),
    ("VO_000186", "System voice (extended)",
     "", "Inferred", "Index 185."),
    
    # --- Additional voices (later additions, non-sequential indices >= 204) ---
    ("VO_000205", "System voice (later addition)",
     "", "Inferred", "Index 204. Non-sequential placement suggests later game update."),
    ("VO_000207", "System voice (later addition)",
     "", "Inferred", "Index 206."),
    ("VO_000208", "System voice (later addition)",
     "", "Inferred", "Index 207."),
    ("VO_000209", "System voice / Movie player",
     "", "Inferred", "Index 208. Movie player-related (appears in MovieController params but as movie ID, not voice)."),
    ("VO_000210", "System voice (later addition)",
     "", "Inferred", "Index 209."),
    ("VO_000223", "System voice (photo edit block)",
     "", "Inferred", "Index 222. Adjacent to confirmed photo edit voices."),
    ("VO_000224", "Photo edit menu voice 1",
     "PhotoEditProcess.MainMenuUpdate; PhotoEditProcess.UnregisteredUpdate",
     "Confirmed", "Voice during photo edit main menu and unregistered state."),
    ("VO_000225", "Photo edit menu voice 2",
     "PhotoEditProcess.MainMenuUpdate",
     "Confirmed", "Second photo edit menu voice at different IL offset from VO_000224."),
    ("VO_000226", "Photo edit confirmation voice",
     "PhotoEditProcess.ConfirmationUpdate",
     "Confirmed", "Voice when confirming photo edit actions."),
    ("VO_000227", "Collection update voice",
     "CollectionProcess.OnUpdate",
     "Confirmed", "Voice during collection screen update. At same IL offset as VO_000015 (conditional)."),
    ("VO_000228", "Common dialog voice (ConstParameter.CommonDialogVoice)",
     "CodeReadProcess.LogicUpdate; TicketSelectMonitor.ViewUpdate; ModeSelectMonitor.ViewUpdate; LoginBonusMonitor.SelectCardFadeInJudgeWait_Update",
     "Confirmed", "The primary common dialog voice. Hardcoded in ConstParameter.CommonDialogVoice = VO_000228. Used across many screens as default dialog voice."),
    ("VO_000229", "System voice (dialog block)",
     "", "Inferred", "Index 228. Adjacent to CommonDialogVoice."),
    ("VO_000230", "System voice (dialog block)",
     "", "Inferred", "Index 229."),
    ("VO_000231", "System voice (dialog block)",
     "", "Inferred", "Index 230."),
    ("VO_000232", "System voice (dialog block)",
     "", "Inferred", "Index 231."),
    ("VO_000235", "System voice (gap)",
     "", "Inferred", "Index 234. Gap after dialog block."),
    ("VO_000238", "System voice",
     "", "Inferred", "Index 237. Before regional select voices."),
    ("VO_000239", "Regional select voice 1",
     "RegionalSelectProcess.RegionSelectDecide",
     "Confirmed", "One of 6 conditional region select voices (switch on region type)."),
    ("VO_000240", "Regional select voice 2",
     "RegionalSelectProcess.RegionSelectDecide",
     "Confirmed", "Region select voice for a specific region type."),
    ("VO_000241", "Regional select voice 3 / SE: Touch confirm (dual use)",
     "RegionalSelectProcess.RegionSelectDecide (PlayVoice); ALSO many PlaySE calls across screens",
     "Confirmed", "As voice: region select voice. As SE (cue 240): the most common touch/confirm sound effect. NOTE: same cue index used in SE ACB for touch effects."),
    ("VO_000242", "Regional select voice 4",
     "RegionalSelectProcess.RegionSelectDecide",
     "Confirmed", "Region select voice for a specific region type."),
    
    # --- Latest additions (very high non-sequential indices 242+) ---
    ("VO_000255", "System voice (latest additions)",
     "", "Inferred", "Index 242. Late addition block start."),
    ("VO_000256", "System voice (latest additions)",
     "", "Inferred", "Index 243."),
    ("VO_000257", "System voice (latest additions)",
     "", "Inferred", "Index 244."),
    ("VO_000258", "Result screen - Rank achievement voice 1",
     "MapResultMonitor.ViewUpdate",
     "Confirmed", "Voice during result screen at IL offset 5894. Plays for rank display."),
    ("VO_000259", "Result screen - Rank achievement voice 2",
     "MapResultMonitor.ViewUpdate",
     "Confirmed", "Voice during result screen at IL offset 5995. Plays after VO_000258 for higher rank."),
    ("VO_000260", "System voice (result block)",
     "", "Inferred", "Index 247. Adjacent to confirmed result voices."),
    ("VO_000261", "System voice (result block)",
     "", "Inferred", "Index 248."),
    ("VO_000262", "System voice (result block)",
     "", "Inferred", "Index 249."),
    ("VO_000263", "Mode select specific voice",
     "ModeSelectMonitor.ViewUpdate",
     "Confirmed", "Mode select voice at IL offset 1225, separate from the multi-branch at offset 915."),
    
    # --- Appended entries (indices 251+, added in later updates) ---
    ("VO_000103", "System voice (appended)",
     "", "Inferred", "Index 251. Appended to end of enum in later update."),
    ("VO_000104", "System voice (appended)",
     "", "Inferred", "Index 252."),
    ("VO_000109", "System voice (appended)",
     "", "Inferred", "Index 253."),
    ("VO_000112", "Option select start voice",
     "Process.SubSequence.OptionSelectSequence.OnStartSequence",
     "Confirmed", "Voice when entering the option/settings select screen."),
    ("VO_000114", "System voice (appended)",
     "", "Inferred", "Index 255."),
    ("VO_000206", "System voice (appended)",
     "", "Inferred", "Index 256."),
    ("VO_000099", "System voice (appended)",
     "", "Inferred", "Index 257. Also exists in partner voice map (partner index 7)."),
    ("VO_000101", "System voice (appended)",
     "", "Inferred", "Index 258. Also exists in partner voice map (partner index 8)."),
    ("VO_000133", "Unlock notification voice",
     "Monitor.UnlockMonitor.UnlockCheck",
     "Confirmed", "Voice when checking/displaying an unlock event."),
    ("VO_000151", "System voice (appended)",
     "", "Inferred", "Index 260."),
    ("VO_000152", "System voice (appended)",
     "", "Inferred", "Index 261."),
    ("VO_000153", "System voice (appended)",
     "", "Inferred", "Index 262."),
    ("VO_000155", "System voice (appended)",
     "", "Inferred", "Index 263."),
    ("VO_000157", "System voice (appended)",
     "", "Inferred", "Index 264."),
    ("VO_000158", "System voice (appended)",
     "", "Inferred", "Index 265."),
    ("VO_000159", "System voice (appended)",
     "", "Inferred", "Index 266."),
    ("VO_000182", "System voice (appended)",
     "", "Inferred", "Index 267. Also exists in partner voice map (partner index 40)."),
    ("VO_000184", "System voice (appended)",
     "", "Inferred", "Index 268. Also exists in partner voice map (partner index 41)."),
    ("VO_000187", "Score kind change voice (DX score)",
     "MusicSelectSequence.ScoreKindChange",
     "Confirmed", "Voice when switching score kind (e.g., to DX Score). At IL offset 37."),
    ("VO_000188", "Score kind change voice (Standard score)",
     "MusicSelectSequence.ScoreKindChange",
     "Confirmed", "Voice when switching score kind (e.g., to Standard). At IL offset 81."),
    ("VO_000189", "System voice (appended)",
     "", "Inferred", "Index 271."),
    ("VO_000247", "System voice (appended)",
     "", "Inferred", "Index 272."),
    ("VO_000248", "Simple setting process voice",
     "SimpleSettingMonitor+<PlayCoroutine>.MoveNext",
     "Confirmed", "Voice during simple settings coroutine, at IL offset 269."),
    ("VO_000253", "System voice (appended)",
     "", "Inferred", "Index 274."),
    ("VO_000264", "System voice (appended)",
     "", "Inferred", "Index 275."),
    ("VO_000265", "System voice (appended) / Partner room entry (see partner voice)",
     "", "Inferred", "Index 276. Also VO_000265 in partner voice map (index 93) = partnerRoomEntryVoice from all Partner.xml files."),
]

# ============================================================
# PARTNER VOICE CONFIRMED MAPPINGS
# Source: deep_voice_analysis.txt scan for SoundManager.PlayPartnerVoice
# NOTE: The mod's scan sometimes reported System Voice VO names for
#       Partner Voice calls (bug). Where applicable, the correct
#       Partner Voice VO_ID has been resolved using the Partner Voice
#       Cue Map. The integer index in parentheses is always correct.
# ============================================================

PARTNER_VOICE_DATA = [
    # --- Login Bonus ---
    ("VO_000080", "Partner: Default / base voice (index 0)",
     "ResultProcess.LogicUpdate (possibly target param); SortSettingSequence.Update (possibly target)",
     "Inferred", "Partner cue index 0. Appears in scan but often as target parameter. May be the default/fallback partner voice."),
    ("VO_000081", "Partner: Login bonus / sort setting greeting",
     "LoginBonusMonitor.GetCharacterFadeOutWait1_Update; SortSettingSequence.OnStartSequence (conditional)",
     "Inferred", "Partner cue index 1. Appears alongside other cues; may be target param in some contexts."),
    ("VO_000084", "Partner: Voice line (index 2)",
     "", "Inferred", "Partner cue index 2."),
    ("VO_000085", "Partner: Voice line (index 3)",
     "", "Inferred", "Partner cue index 3."),
    ("VO_000086", "Partner: Voice line (index 4)",
     "", "Inferred", "Partner cue index 4."),
    ("VO_000087", "Partner: Voice line (index 5)",
     "", "Inferred", "Partner cue index 5."),
    ("VO_000088", "Partner: Voice line (index 6)",
     "", "Inferred", "Partner cue index 6."),
    
    # --- Music Select Subsequence Partner Voices ---
    ("VO_000099", "Partner: Difficulty select voice",
     "Process.SubSequence.DifficultySelectSequence.OnStartSequence",
     "Confirmed", "Partner voice when entering difficulty selection screen. Partner cue index 7."),
    ("VO_000101", "Partner: Menu select voice / VoiceCheck",
     "MenuSelectSequence.OnStartSequence; MenuSelectSequence.VoiceCheck",
     "Confirmed", "Partner voice when menu selection starts and during voice check. Partner cue index 8."),
    ("VO_000113", "Partner: Voice line (index 9)",
     "", "Inferred", "Partner cue index 9."),
    ("VO_000114", "Partner: Voice line (index 10)",
     "", "Inferred", "Partner cue index 10."),
    ("VO_000116", "Partner: Voice line (index 11)",
     "", "Inferred", "Partner cue index 11."),
    ("VO_000118", "Partner: Voice line (index 12)",
     "", "Inferred", "Partner cue index 12."),
    ("VO_000119", "Partner: Voice line (index 13)",
     "", "Inferred", "Partner cue index 13."),
    ("VO_000120", "Partner: Voice line (index 14)",
     "", "Inferred", "Partner cue index 14."),
    ("VO_000121", "Partner: Voice line (index 15)",
     "", "Inferred", "Partner cue index 15."),
    ("VO_000122", "Partner: Voice line (index 16)",
     "", "Inferred", "Partner cue index 16."),
    ("VO_000123", "Partner: Voice line (index 17)",
     "", "Inferred", "Partner cue index 17."),
    ("VO_000124", "Partner: Voice line (index 18)",
     "", "Inferred", "Partner cue index 18."),
    ("VO_000125", "Partner: Voice line (index 19)",
     "", "Inferred", "Partner cue index 19."),
    ("VO_000126", "Partner: Voice line (index 20)",
     "", "Inferred", "Partner cue index 20."),
    ("VO_000127", "Partner: Voice line (index 21)",
     "", "Inferred", "Partner cue index 21."),
    ("VO_000128", "Partner: Voice line (index 22)",
     "", "Inferred", "Partner cue index 22."),
    ("VO_000129", "Partner: Voice line (index 23)",
     "", "Inferred", "Partner cue index 23."),
    ("VO_000130", "Partner: Voice line (index 24)",
     "", "Inferred", "Partner cue index 24."),
    ("VO_000131", "Partner: Voice line (index 25)",
     "", "Inferred", "Partner cue index 25."),
    ("VO_000133", "Partner: Voice line (index 26)",
     "", "Inferred", "Partner cue index 26. Also exists in system voice map (index 259) for unlock notifications."),
    ("VO_000139", "Partner: Voice line (index 27)",
     "", "Inferred", "Partner cue index 27."),
    ("VO_000141", "Partner: Voice line (index 28)",
     "", "Inferred", "Partner cue index 28."),
    ("VO_000151", "Partner: Voice line (index 29)",
     "", "Inferred", "Partner cue index 29."),
    ("VO_000152", "Partner: Voice line (index 30)",
     "", "Inferred", "Partner cue index 30."),
    ("VO_000153", "Partner: Voice line (index 31)",
     "", "Inferred", "Partner cue index 31."),
    ("VO_000155", "Partner: Voice line (index 32)",
     "", "Inferred", "Partner cue index 32."),
    ("VO_000157", "Partner: Voice line (index 33)",
     "", "Inferred", "Partner cue index 33."),
    ("VO_000158", "Partner: Voice line (index 34)",
     "", "Inferred", "Partner cue index 34."),
    ("VO_000159", "Partner: Voice line (index 35)",
     "", "Inferred", "Partner cue index 35."),
    
    # --- Game Flow Partner Voices ---
    ("VO_000164", "Partner: Continue screen voice",
     "Process.ContinueProcess.OnUpdate",
     "Confirmed", "Partner voice during continue screen. Mod reported as VO_000037(36) using system map; correct partner ID is VO_000164 at partner index 36."),
    ("VO_000165", "Partner: Voice line (index 37)",
     "", "Inferred", "Partner cue index 37. Adjacent to confirmed continue voice."),
    ("VO_000166", "Partner: Game over voice 1",
     "Process.GameOverProcess.OnUpdate",
     "Confirmed", "First partner voice during game over screen. Partner cue index 38."),
    ("VO_000167", "Partner: Game over voice 2",
     "Process.GameOverProcess.OnUpdate",
     "Confirmed", "Second partner voice during game over. Mod reported VO_000040(39); correct partner ID is VO_000167 at index 39."),
    ("VO_000182", "Partner: Genre select voice",
     "Process.SubSequence.GenreSelectSequence.OnStartSequence",
     "Confirmed", "Partner voice when entering genre selection. Partner cue index 40."),
    ("VO_000184", "Partner: Music select voice",
     "Process.SubSequence.MusicSelectSequence.OnStartSequence",
     "Confirmed", "Partner voice when entering music selection. Partner cue index 41."),
    ("VO_000187", "Partner: Voice line (index 42)",
     "", "Inferred", "Partner cue index 42. Also exists in system voice map (index 269) for score kind change."),
    ("VO_000188", "Partner: Voice line (index 43)",
     "", "Inferred", "Partner cue index 43."),
    ("VO_000189", "Partner: Sort setting start voice",
     "Process.SubSequence.SortSettingSequence.OnStartSequence",
     "Confirmed", "Partner voice when entering sort settings. Partner cue index 44."),
    
    # --- Partner Voices for specific functions ---
    ("VO_000200", "Partner: Voice line (index 45)",
     "", "Inferred", "Partner cue index 45."),
    ("VO_000201", "Partner: Voice line (index 46)",
     "", "Inferred", "Partner cue index 46."),
    ("VO_000202", "Partner: Voice line (index 47)",
     "", "Inferred", "Partner cue index 47."),
    ("VO_000203", "Partner: Voice line (index 48)",
     "", "Inferred", "Partner cue index 48."),
    ("VO_000204", "Partner: Voice line (index 49)",
     "", "Inferred", "Partner cue index 49."),
    ("VO_000211", "Partner: Voice line (index 50)",
     "", "Inferred", "Partner cue index 50."),
    ("VO_000213", "Partner: Voice line (index 51)",
     "", "Inferred", "Partner cue index 51."),
    ("VO_000214", "Partner: Voice line (index 52)",
     "", "Inferred", "Partner cue index 52."),
    ("VO_000217", "Partner: Voice line (index 53)",
     "", "Inferred", "Partner cue index 53."),
    ("VO_000220", "Partner: Voice line (index 54)",
     "", "Inferred", "Partner cue index 54."),
    ("VO_000222", "Partner: Voice line (index 55)",
     "", "Inferred", "Partner cue index 55."),
    ("VO_000244", "Partner: Voice line (index 56)",
     "", "Inferred", "Partner cue index 56."),
    ("VO_000245", "Partner: Voice line (index 57)",
     "", "Inferred", "Partner cue index 57."),
    ("VO_000246", "Partner: Voice line (index 58)",
     "", "Inferred", "Partner cue index 58."),
    ("VO_000247", "Partner: Voice line (index 59)",
     "", "Inferred", "Partner cue index 59."),
    
    # --- Later-added partner voices (non-sequential indices 60+) ---
    ("VO_000082", "Partner: Voice line (index 60)",
     "", "Inferred", "Partner cue index 60. Added in later update."),
    ("VO_000083", "Partner: Voice line (index 61)",
     "", "Inferred", "Partner cue index 61."),
    ("VO_000115", "Partner: Login bonus character voice",
     "LoginBonusMonitor.GetCharacterFadeOutWait1_Update",
     "Confirmed", "Partner voice during login bonus character fade transition. Partner cue index 62. Mod reported as VO_000063(62) using system map."),
    ("VO_000117", "Partner: Voice line (index 63)",
     "", "Inferred", "Partner cue index 63."),
    ("VO_000248", "Partner: Voice line (index 64)",
     "", "Inferred", "Partner cue index 64."),
    ("VO_000249", "Partner: Shop partner get voice",
     "ShopPartnerGetWindow.PlayPartnerVoice (coroutine)",
     "Confirmed", "Partner voice when obtaining a new partner from the shop. Partner cue index 65. Mod reported as VO_000066(65) using system map."),
    ("VO_000250", "Partner: Login bonus greeting / card select voice",
     "LoginBonusMonitor.Initialize; LoginBonusMonitor.SelectCardDecideInit_Update",
     "Confirmed", "Partner greeting during login bonus and when selecting login bonus card. Partner cue index 66."),
    ("VO_000251", "Partner: Partner room / partner sequence voice",
     "CollectionProcess.InputPartnerSequence",
     "Confirmed", "Partner voice during partner selection in collection/customization room. Partner cue index 67."),
    ("VO_000252", "Partner: Touch / Result partner voice",
     "CollectionProcess.TouchProcess; ResultProcess.LogicUpdate",
     "Confirmed", "Partner voice when touching partner and during result screen. Partner cue index 68."),
    
    # --- Appended partner voices (indices 69+) ---
    ("VO_000103", "Partner: Voice line (index 69)",
     "", "Inferred", "Partner cue index 69."),
    ("VO_000104", "Partner: Voice line (index 70)",
     "", "Inferred", "Partner cue index 70."),
    ("VO_000109", "Partner: Voice line (index 71)",
     "", "Inferred", "Partner cue index 71."),
    ("VO_000112", "Partner: Voice line (index 72)",
     "", "Inferred", "Partner cue index 72."),
    
    # --- Sort type partner voices (confirmed block) ---
    ("VO_000190", "Partner: Sort type voice - Type 1",
     "SortSettingSequence.Update",
     "Confirmed", "Partner voice for sort type selection option 1. Partner cue index 73. Part of switch statement on sort type."),
    ("VO_000191", "Partner: Sort type voice - Type 2",
     "SortSettingSequence.Update",
     "Confirmed", "Partner voice for sort type selection option 2. Partner cue index 74. Mod incorrectly reported as VO_000075."),
    ("VO_000192", "Partner: Sort type voice - Type 3",
     "SortSettingSequence.Update",
     "Confirmed", "Partner voice for sort type selection option 3. Partner cue index 75. Mod incorrectly reported as VO_000076."),
    ("VO_000193", "Partner: Sort type voice - Type 4",
     "SortSettingSequence.Update",
     "Confirmed", "Partner voice for sort type selection option 4. Partner cue index 76. Mod incorrectly reported as VO_000077."),
    ("VO_000194", "Partner: Sort type voice - Type 5",
     "SortSettingSequence.Update",
     "Confirmed", "Partner voice for sort type selection option 5. Partner cue index 77."),
    ("VO_000195", "Partner: Sort type voice - Type 6",
     "SortSettingSequence.Update",
     "Confirmed", "Partner voice for sort type selection option 6. Partner cue index 78."),
    ("VO_000196", "Partner: Voice line (index 79 - no confirmed caller)",
     "", "Inferred", "Partner cue index 79. In sort type block but not seen in scan."),
    ("VO_000197", "Partner: Sort type voice - Type 7",
     "SortSettingSequence.Update",
     "Confirmed", "Partner voice for sort type selection option 7. Partner cue index 80."),
    ("VO_000198", "Partner: Sort type voice - Type 8",
     "SortSettingSequence.Update",
     "Confirmed", "Partner voice for sort type selection option 8. Partner cue index 81."),
    ("VO_000199", "Partner: Sort type voice - Type 9",
     "SortSettingSequence.Update",
     "Confirmed", "Partner voice for sort type selection option 9. Partner cue index 82."),
    
    # Note: Partner index 83 is MISSING from the enum
    
    ("VO_000206", "Partner: Voice line (index 84)",
     "", "Inferred", "Partner cue index 84. Note: index 83 is missing."),
    ("VO_000243", "Partner: Voice line (index 85)",
     "", "Inferred", "Partner cue index 85."),
    ("VO_000253", "Partner: Voice line (index 86)",
     "", "Inferred", "Partner cue index 86."),
    ("VO_000254", "Partner: Voice line (index 87)",
     "", "Inferred", "Partner cue index 87."),
    ("VO_000142", "Partner: Voice line (index 88)",
     "", "Inferred", "Partner cue index 88. Same VO_ID as system SE cue 141 (tab press) but different ACB/audio."),
    ("VO_000207", "Partner: Voice line (index 89)",
     "", "Inferred", "Partner cue index 89."),
    ("VO_000208", "Partner: Voice line (index 90)",
     "", "Inferred", "Partner cue index 90."),
    ("VO_000209", "Partner: Voice line (index 91)",
     "", "Inferred", "Partner cue index 91."),
    ("VO_000210", "Partner: Voice line (index 92)",
     "", "Inferred", "Partner cue index 92."),
    ("VO_000265", "Partner: Partner room entry voice",
     "CollectionProcess.PlayPartnerRoomEntryVoice (coroutine); All Partner.xml partnerRoomEntryVoice field",
     "Confirmed", "Voice when partner enters the partner room. Partner cue index 93. All 26 Partner.xml files set partnerRoomEntryVoice=VO_000265."),
    ("VO_000266", "Partner: Intimate-up voice 1 / Bond level up",
     "CollectionProcess.PlayIntimateUpVoiceRandom (selects from intimateUpVoice01/02/03); All Partner.xml intimateUpVoice01 field",
     "Confirmed", "Voice when partner bond/intimacy level increases. Partner cue index 94. Selected randomly from intimateUpVoice01/02/03 list via PlayIntimateUpVoiceRandom()."),
]


def build_csv():
    rows = []
    
    # System Voice entries
    for vo_id, context, callers, evidence, notes in SYSTEM_VOICE_DATA:
        cue_idx = SYSTEM_VOICE_MAP.get(vo_id, "?")
        also_partner = "Yes" if vo_id in PARTNER_VOICE_MAP else "No"
        rows.append({
            "VO_ID": vo_id,
            "Cue_Index": cue_idx,
            "Voice_Type": "System",
            "ACB_File": "Voice_000001",
            "Game_Context": context,
            "Caller_Methods": callers,
            "Evidence": evidence,
            "Also_In_Other_Voice_Map": also_partner,
            "Notes": notes,
        })
    
    # Partner Voice entries
    for vo_id, context, callers, evidence, notes in PARTNER_VOICE_DATA:
        cue_idx = PARTNER_VOICE_MAP.get(vo_id, "?")
        also_system = "Yes" if vo_id in SYSTEM_VOICE_MAP else "No"
        rows.append({
            "VO_ID": vo_id,
            "Cue_Index": cue_idx,
            "Voice_Type": "Partner",
            "ACB_File": "Voice_Partner_XXXXXX",
            "Game_Context": context,
            "Caller_Methods": callers,
            "Evidence": evidence,
            "Also_In_Other_Voice_Map": also_system,
            "Notes": notes,
        })
    
    # Write CSV
    fieldnames = ["VO_ID", "Cue_Index", "Voice_Type", "ACB_File", "Game_Context", 
                  "Caller_Methods", "Evidence", "Also_In_Other_Voice_Map", "Notes"]
    
    output_path = r"D:\maimai circle voice and partner data\voice_action_mapping.csv"
    with open(output_path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    
    # Stats
    sys_count = len(SYSTEM_VOICE_DATA)
    ptr_count = len(PARTNER_VOICE_DATA)
    sys_confirmed = sum(1 for _, _, _, e, _ in SYSTEM_VOICE_DATA if e == "Confirmed")
    ptr_confirmed = sum(1 for _, _, _, e, _ in PARTNER_VOICE_DATA if e == "Confirmed")
    total = sys_count + ptr_count
    total_confirmed = sys_confirmed + ptr_confirmed
    
    print(f"CSV written to: {output_path}")
    print(f"Total entries: {total}")
    print(f"  System Voice: {sys_count} ({sys_confirmed} confirmed)")
    print(f"  Partner Voice: {ptr_count} ({ptr_confirmed} confirmed)")
    print(f"  Total confirmed: {total_confirmed}/{total} ({100*total_confirmed//total}%)")
    print(f"\nSystem Voice enum has {len(SYSTEM_VOICE_MAP)} entries")
    print(f"Partner Voice enum has {len(PARTNER_VOICE_MAP)} entries")
    
    # Check coverage
    sys_covered = set(vo for vo, _, _, _, _ in SYSTEM_VOICE_DATA)
    ptr_covered = set(vo for vo, _, _, _, _ in PARTNER_VOICE_DATA)
    sys_missing = set(SYSTEM_VOICE_MAP.keys()) - sys_covered
    ptr_missing = set(PARTNER_VOICE_MAP.keys()) - ptr_covered
    
    if sys_missing:
        print(f"\nWARNING: {len(sys_missing)} system voice IDs not in CSV: {sorted(sys_missing)}")
    if ptr_missing:
        print(f"WARNING: {len(ptr_missing)} partner voice IDs not in CSV: {sorted(ptr_missing)}")


if __name__ == "__main__":
    build_csv()
